default:
  rhino_log_level: !expr Sys.getenv("RHINO_LOG_LEVEL", "INFO")
  rhino_log_file: !expr Sys.getenv("RHINO_LOG_FILE", NA)
  mysql:
    user: "user"
    password: "password"
    port: "3306"

deploy:
  mysql:
    host: !expr Sys.getenv("MYSQL_HOST")
    user: !expr Sys.getenv("MYSQL_USER")
    password: !expr Sys.getenv("MYSQL_PASSWORD")
    port: !expr Sys.getenv("MYSQL_PORT")

compose:
  mysql:
    host: "db"

local:
  mysql:
    host: "127.0.0.1"

none:
  mysql:
    host: NULL
