# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(assertr)
library(bsicons)
library(DT)
library(dplyr)
library(furrr)
library(openxlsx)
library(readxl)
library(rhino)
library(RMariaDB)
library(rvest)
library(shinyjs)
library(shinyvalidate)
library(shinyWidgets)
library(waiter)
library(logger)
