version: "3"
services:
  shiny:
    build:
      context: .
      dockerfile: shiny_docker
    environment:
      - GITHUB_ACTIONS=true
    ports:
      - "8080:8080"
    volumes:
      - renv-cache:/root/.cache/R/renv/cache/v5/R-4.3/aarch64-unknown-linux-gnu

  db:
    build:
      context: .
      dockerfile: mysql_docker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Publications
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  
volumes:
  renv-cache:
  db_data:
